@startuml
set separator none
title Software Difusión de Contenidos - Message Broker - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container(SoftwareDifusióndeContenidos.DBMSDifusióndeContenidos, "DBMS Difusión de Contenidos", "", $tags="")
Container(SoftwareDifusióndeContenidos.UCampus, "U-Campus", "", $tags="")
Container(SoftwareDifusióndeContenidos.UPapers, "U-Papers", "", $tags="")

Container_Boundary("SoftwareDifusióndeContenidos.MessageBroker_boundary", "Message Broker", $tags="") {
  Component(SoftwareDifusióndeContenidos.MessageBroker.PublicadorUCampus, "Publicador U-Campus", "", $tags="")
  Component(SoftwareDifusióndeContenidos.MessageBroker.PublicadorUPaper, "Publicador U-Paper", "", $tags="")
  Component(SoftwareDifusióndeContenidos.MessageBroker.SubcriptorUCampus, "Subcriptor U-Campus", "", $tags="")
  Component(SoftwareDifusióndeContenidos.MessageBroker.SubcriptorUPaper, "Subcriptor U-Paper", "", $tags="")
}

Rel_D(SoftwareDifusióndeContenidos.MessageBroker.PublicadorUCampus, SoftwareDifusióndeContenidos.MessageBroker.SubcriptorUCampus, "subcribe replica estructura", $tags="")
Rel_D(SoftwareDifusióndeContenidos.MessageBroker.SubcriptorUCampus, SoftwareDifusióndeContenidos.DBMSDifusióndeContenidos, "recibe replica estructura", $tags="")
Rel_D(SoftwareDifusióndeContenidos.MessageBroker.PublicadorUPaper, SoftwareDifusióndeContenidos.MessageBroker.SubcriptorUPaper, "subcribe replica papers", $tags="")
Rel_D(SoftwareDifusióndeContenidos.MessageBroker.SubcriptorUPaper, SoftwareDifusióndeContenidos.DBMSDifusióndeContenidos, "recibe replica papers", $tags="")
Rel_D(SoftwareDifusióndeContenidos.UPapers, SoftwareDifusióndeContenidos.MessageBroker.PublicadorUPaper, "replica papers", $tags="")
Rel_D(SoftwareDifusióndeContenidos.UCampus, SoftwareDifusióndeContenidos.MessageBroker.PublicadorUCampus, "replica estructura", $tags="")

SHOW_LEGEND(true)
@enduml