@startuml
set separator none
title Software Difusión de Contenidos - Gateway - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container(SoftwareDifusióndeContenidos.DBMSDifusióndeContenidos, "DBMS Difusión de Contenidos", "", $tags="")
Container(SoftwareDifusióndeContenidos.UNoticia, "U-Noticia", "", $tags="")
Container(SoftwareDifusióndeContenidos.SitioWebPublico, "Sitio Web Publico", "nextjs", "", $tags="")

Container_Boundary("SoftwareDifusióndeContenidos.Gateway_boundary", "Gateway", $tags="") {
  Component(SoftwareDifusióndeContenidos.Gateway.APIUNoticias, "API U-Noticias", "", $tags="")
  Component(SoftwareDifusióndeContenidos.Gateway.APIDifusiondeContenido, "API Difusion de Contenido", "", $tags="")
}

Rel_D(SoftwareDifusióndeContenidos.SitioWebPublico, SoftwareDifusióndeContenidos.Gateway.APIDifusiondeContenido, "conecta con api", $tags="")
Rel_D(SoftwareDifusióndeContenidos.Gateway.APIDifusiondeContenido, SoftwareDifusióndeContenidos.DBMSDifusióndeContenidos, "Lee y escribe", $tags="")
Rel_D(SoftwareDifusióndeContenidos.Gateway.APIDifusiondeContenido, SoftwareDifusióndeContenidos.Gateway.APIUNoticias, "crea noticia", $tags="")
Rel_D(SoftwareDifusióndeContenidos.Gateway.APIUNoticias, SoftwareDifusióndeContenidos.UNoticia, "crea noticia", $tags="")

SHOW_LEGEND(true)
@enduml