@startuml
set separator none
title Deployment - Web Server

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Deployment>

Deployment_Node(WebServer.WebApp, "WebApp", $tags="") {
  Container(WebServer.WebApp.SitioWebPublico_1, "Sitio Web Publico", "nextjs", "", $tags="")
}


SHOW_LEGEND(true)
@enduml